baseURL = 'https://mollycarroll.dev'
languageCode = 'en-us'
title = 'technically Molly'
copyright = 'Molly Carroll'
enableRobotsTXT = true

enableInlineShortcodes = true

[params]
# Set how dates should appear across the site.
# For format options, visit https://gohugo.io/functions/time/format/
dateFormat = ':date_long'

# Show content graph for single notes and posts.
# Default: true
showGraph = true

# Author details for the JSON-LD structured data.
[params.author]
name = 'Molly Carroll'
email = 'molly@mollycarroll.dev'

# Homepage setup
[params.home]
# Display recent blog posts on the homepage.
# Default: true
showRecentPosts = true

# Set how many recent blog posts to show.
# Default: 3
recentPostsLimit = 3

# Display recent notes on the homepage.
# Default: true
showRecentNotes = false

# Set how many recent notes to show.
# Default: 5
recentNotesLimit = 4

# Notes page setup
[params.notes]
# Set the number of notes to list on each page.
# Default: 20
pageSize = 13

# Show a filter option for note categories above the notes list.
# Default: true
showCategoryFilter = true

# Footer setup
[params.footer]
# Specify the Creative Commons license to apply to your content.
# Learn more at https://creativecommons.org/share-your-work/cclicenses/
creativeCommonsLicense = 'by'

# Show Creative Commons icons for the selected license.
# Default: true
showCreativeCommonsIcons = true

# Show a credit link to the Today I Learned theme in the footer.
# Default: true
showThemeCredit = true

# robots.txt setup
[params.robotstxt]
# Block CommonCrawl from indexing your site. CommonCrawl data is often used to train AI models.
# Learn more at https://commoncrawl.org/ccbot
# Default: false
blockCC = false

# Block various crawlers associated with AI and machine learning model training.
# Crawler list from https://github.com/ai-robots-txt/ai.robots.txt
# Default: false
blockAI = true

titleCaseStyle = 'firstupper'

[outputs]
home = ['html']
section = ['html', 'rss', 'json']
page = ['html']

[menus]
[[menus.main]]
name = 'Resume'
pageRef = '/about/resume.md'
weight = 1
[[menus.main]]
name = 'Consulting'
pageRef = '/about/consulting.md'
weight = 2
[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 3
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 4
[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 5
[[menus.main]]
name = 'Graph'
pageRef = '/graph'
weight = 6

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = false

[markup.highlight]
noClasses = false
style = 'monokai'

[taxonomies]
category = 'categories'
series = 'series'
tags = 'tags'
track = 'tracks'

[caches]
[caches.images]
dir = ':cacheDir/images'
